sources:
  - name: HpApi
    handler:
      jsonSchema:
        endpoint: http://hp-api.onrender.com/api
        operations:
          - type: Query
            field: characters
            path: /characters
            method: GET
            responseSample: ./characters/sample.json
